### ISSUE TITLE
Cloud Management and visualisation

### ISSUE THREAD

**Issue by MatsBJohansson** [eclipse-arrowhead/roadmap#10]
For enhancing the Eclipse Arrowhead utilisation it would be beneficial to have a more appealing overview presentation of which systems are available and which services can they produce and/or consume. Both for designing local clouds and also for deployment and runtime monitoring and orchestration. 
Both core- and application- systems and services should be covered. Example of a view of available systems and what services they can produce and consume is shown in attached picture (from the previous Arrowhead project), as food for thought. Would be great to be able to extract something like that from the SysML model (not to add maintenance effort).

Then we would also like a graphical tool that shows which systems are selected for a specific local cloud and which systems shall consume which services (instance level)  (orchestration), which then support the first deployment and the runtime monitoring and orchestration.

![SystemServiceMatrix](https://user-images.githubusercontent.com/82516911/114713306-4914f280-9d31-11eb-9d74-69d0443d2b66.JPG)

**Comment by emanuelpalm** [comment]
@MatsBJohansson The orchestration visuals you are requesting are proposed for the Cloud Manager system (a rework of the existing Management Tool). If you could list things you would like the Cloud Manager to visualize, and how, please look at #3 and make suggestions. :)

**Comment by jerkerdelsing** [comment]
Merge with #3
