### ISSUE TITLE
X.509 Profile for Arrowhead

### ISSUE THREAD

**Issue by emanuelpalm** [eclipse-arrowhead/roadmap#11]
__EDIT: Review for my profiles proposal is on-going. Please get a copy and make your comments [here](https://github.com/arrowhead-f/x509-profiles/pull/3).__

EDIT: This discussion has been moved [here](https://github.com/arrowhead-f/x509-profiles). This thread remains for two reasons: (1) as a reminder that the issue is still yet to be resolved and (2) to leave a record of the discussions.

Right now, five (?) kinds of certificates are used within Arrowhead. These are:
- The Arrowhead Root (arrowhead.eu)
- Cloud certificates (cloud-name.company-name.arrowhead.eu)
- System certificates (system-name.cloud-name.company-name.arrowhead.eu)
- Device certificates
- On-boarding certificates

@mzsilak @tsvetlin would perhaps be aware of other types of certificates?

To make it clear how certificates relate to authentication/authorization, what extensions and/or other fields should be used, I propose that we create our own x.509 ~~protocol~~ profile, which would be a document outlining what kinds of certificates exist, how they are identified and what fields and/or extensions we would expect them to use. Some attempt to make our _profile_ compatible with [RFC5280](https://tools.ietf.org/html/rfc5280.html) would most likely be relevant, as that would make our certificates work better with existing Internet-related tools and libraries. That would include using the basic constraints and subject alternative names extensions, as well as other such.

Could we perhaps try to list all certificate details we currently rely on for different reasons in this issue?

**Comment by emanuelpalm** [comment]
Apparently, I was mistaken about the name of the kind of document I am looking for. It's supposed to be called _profile_. Another example of such a profile is given [here](https://ec.europa.eu/cefdigital/wiki/download/attachments/37752981/X.509%20Certificate%20Profiles_v2.0.0.pdf?version=1&modificationDate=1532522976601&api=v2).

**Comment by emanuelpalm** [comment]
@jerkerdelsing @tsvetlin @mzsilak Now that #17 is being discussed and a X.509 profile is yet to be decided upon, I would like to raise some concerns I have with the current state of things.

### CA certificates do not require DNS names in their Subject CNs. Why do we have them?

If looking in [RFC5280](https://datatracker.ietf.org/doc/html/rfc5280) (the web X.509 Certificate Profile), no requirements are made regarding what RDNs should be used in the Subject and Issuer fields (which in our case now are to contain the CNs conforming to the above patterns). In [Section 4.1.2.4](https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.4), it is simply stated that at least one of the RDNs `country` (C), `organization` (O), `organizational unit` (OU),  `distinguished name qualifier` (DNQ), `state or province name` (S), `common name` (CN) and `serial number` (SERIALNUMBER) have to be provided. In other words, nothing is said about having DNS names in the common name. It is, however, common practice for non-CA certificates to have domain names (I believe it is for historical reasons). If, for example, looking at the certificate chain of this website (github.com), the site certificate has `CN=github.com`, while its issuer CA has `CN=DigiCert High Assurance TLS Hybrid ECC SHA256 2020 CA1`. As CN names are not required to be validated by browsers (or anyone else), the DNS domain names that are endorsed by GitHub's certificate are listed as _Subject Alternative Names_ (SANs) (`github.com` and `www.github.com`), which _must_ be compared against the DNS name through which the certificate was received.

Why do we use a DNS schema in the Arrowhead certificate CNs at all? SANs are already used in the existing Arrowhead certificates, and are plenty enough to securely associate a system or device with a DNS name or IP-address. If you want to know which cloud a certificate belongs to, it is clearly stated in the Issuer name of its certificate. As far as I can tell, stating the plain system name (without `.localcloud.arrowhead.eu` or equivalent) as CN, the organization name as O and the type of system as DNQ would be enough. A system registry could, for example, have the Subject DN `CN=system-registry,DNQ=system,O=My Company AB`. Please refer to [X.520](https://www.itu.int/rec/T-REC-X.520-201610-S/en) for definitions of the RDNs.

### Should not organizations be able to issue their own Local Cloud Certificates?

As far as I understand, a local cloud is meant to be a fairly small unit, in terms of how many systems it contains (typically far less than 10 000). That means an organization would need many Local Cloud Certificates, and perhaps even change them as parts of their their plants are upgraded, decommissioned or restructured. Will we have a Certificate issuance procedure that is automated and reliable enough for us to be able to provide these companies with all the Local Cloud Certificates they need? The alternative would be for the Arrowhead Root CA to issue Organization Certificates that the companies could use to issue their own Local Cloud Certificates.

### Why do we need an On-Boarding Certificate?

@mzsilak Looking through the preprint of your on-boarding paper, it seems to me as if the only reason this certificate exists is to separate the concerns of the _Onboarding Controller_ (OC) and _Device Registry_ (DR). The OC supports 4 types of on-boarding, while the DR only needs to keep track of one (via an on-boarding certificate retrieved from the OC). However, it is the same Certificate Authority (CA) that issues both the On-Boarding and Device certificates. Do we need a separate type of certificate only to facilitate this separation? The OC could just as well have provided a one-time token with a short lifetime (such as a 256-bit secure random number shared with the CA) that must be provided to the DR. Alternatively, the DR could support all 4 types of on-boarding and have each of them render a Device Certificate instead of an On-Boarding Certificate. I would argue that this would not make the DR stop being a _micro_-service, if that would be the blocking issue.

**Comment by jerkerdelsing** [comment]
**CA certificates do not require DNS names in their Subject CNs. Why do we have them?**
There is a considerable industrial interest in being able too use DNS. BneaeriT indicates that they are interested in enhancing ServiceRegistry with DNS, much like "Consul". This should be brought into the picture. 

**Should not organizations be able to issue their own Local Cloud Certificates?**
Organisation shall be able to use their own certificate base. We can not thigh certificates to arrowhead.eu only.

 **Why do we need an On-Boarding Certificate?**
One point here is handling of expired device and system certificates. At least I will force a need for much shorter life time of these certificates. This might then be the primary responsibility fo the OC. While DR is given the responsibility of having the actual status of enrolled Devices. 

Having both a primary and a secondary responsibility fo micro system then becomes an Arrowhead strategy question.

**Comment by emanuelpalm** [comment]
@jerkerdelsing 

__CA certificates do not require DNS names in their Subject CNs. Why do we have them?__
My point is that there is no standards-adhering system in existence that would fail a DNS-related procedure due to the CN of our certificates not containing DNS-compliant names. Even if we include a domain name in the CN and a local cloud sets up a DNS server that associates each such CN name with an IP address, no system in that local cloud would be required (as per the web standards) to validate the CN domain name against the DNS names. This means that we are free to use the field however we like in our own X.509 profile, without compromising compatibility with RFC5280. Instead of shoe-horning all data we care about into the same field, I propose we use the facilities the X.509 format already provides.

X.509 is used on the web to secure the relation between DNS records and TLS connections. If looking up a DNS record with appropriate security mechanisms in place (i.e. a chain of signatures exists up to one of the root DNS servers), connecting to the IP address it resolves to and then receiving a X.509 certificate that both lists that DNS name (as a Subject Alternative Name) _and_ being issued by a trusted issuer, the connecting client can rely on the established TLS connection leading to the identity established by the received certificate. There are weaknesses to this approach, for which reason there have been some efforts at mitigating them (such as DNS over TLS).

__Should not organizations be able to issue their own Local Cloud Certificates?__
Does that mean that we both allow for organizations to have their own master certificates and their own organization certificates? In my mind, that creates a hierarchy like the following:

```
                                    +---------+
                                    | Master  |
                                    +---------+
                                         A
                                         |
                                         +--------------------+
                                         | n                  | n
                                 +-------+-------+        +---+---+
                                 | Organization  |        | Gate  |
                                 +---------------+        +-------+
                                         A
                                         | n
                        +----------------+----------------+
                        |                |                |
                 +------+------+  +------+------+  +------+------+
                 | Local Cloud |  | Local Cloud |  | Local Cloud |
                 +-------------+  +-------------+  +-------------+
                        A
                        |
       +----------------+
       | n              | n
+------+------+  +------+------+ 
|   Operator  |  |    System   |
+-------------+  +-------------+
```

**Comment by emanuelpalm** [comment]
@jerkerdelsing 

__Why do we need an On-Boarding Certificate?__
Using the On-Boarding certificate as a form of last-resort certificate renewal token could be a good idea. I would assume that the on-boarding certificate would need to have a longer lifespan than the other the other kinds of certificates? Why a certificate and not a token, however? The advantage of certificates is that they are _context free_, in the sense that no context need to be stored outside of the certificate for it to be useful (except for the corresponding private key on the same device). I'm not convinced that this is a good thing in our case, however.

The _On-Boarding_ certificate is only useful within a single _Local Cloud_, and most likely only when interacting with the OC. Lists of revoked certificates must be maintained and checked against whenever an on-boarding certificate is used to prevent explicitly banned devices from obtaining new certificates. This is very much the same kind of situation as if one-time tokens would have been used. In that case, the OC would provide a new on-boarding token every time one is used. It would maintain a list of not-yet used tokens, which can be altered in the case of certificate renewal is to be disabled for individual devices. The advantage I see is that tokens are smaller and more efficiently handled than certificates. There sure are security caveats that have to be worked around, but there are arguably more of them for certificates than one-time tokens.

**Comment by jerkerdelsing** [comment]
Given the existence of the onboarding system and the use of certificates instead of tokens. I think we should work towards extending the certificate idea to handle create an update process with shorter certificate life time based on full certificates not tokens.

**Comment by mzsilak** [comment]
The idea was to allow 3rd party certificates (manufacturer certificates), or at least hardware secured key-pairs to be used as entry points into arrowhead. The onboarding and device certificates are supposed to be short-lived and only useful for retrieving another system certificate. 

My opinion on the short-life of those certificates changes with Emanuels work on Cloud Bootstrapping as those systems and service might use the onboarding and device certificates.

The use of tokens for onboarding creates a direct link between the systems of the onboarding procedure which does not exist currently. I am not sure about the benefits of using a more lightweight, but proprietary solution.

**Comment by emanuelpalm** [comment]
@mzsilak If you look [here](https://github.com/arrowhead-f/x509-profiles/pull/3), you can tell that I do not mention the manufacturer certificate in that profile. The reason is not that we shouldn't let them exist, but that I realized that there is no need to force those certificates to comply to any particular profile. I believe we should create a separate set of profiles for various types of on-boarding-related certificates if we should see the need arise in the future.

Yes, the coming Device Agent system (new name for Device Bootstrapper) will pretty much be the only on-boarding implementation needed for most kinds of use cases, which I guess changes a few things. Tokens could be a great way to facilitate device certificate renewal, but they don't help us with the first on-boarding to a new cloud. A manufacturer's certificate would be a great way of facilitating that, I believe.

**Comment by jerkerdelsing** [comment]
Eclipse Arrowhead X.509 profile document published in the Documentation repo.
