### ISSUE TITLE
Changelog required

### ISSUE THREAD

**Issue by awoSYS** [eclipse-arrowhead/roadmap#23]
Hey everyone,
I'd propose to create and maintain a changelog, summarizing the changes to the framework in each release.
The obvious argument for that is that it's probably good practice to have a changelog.
Additionally, there are multiple libraries, implementation examples and pieces of documentation out there, all referring to a specific version of the framework. A well-maintained changelog would help to understand, if these things still apply to the current version of the AHFW or what might have changed since then.
I hope I didn't miss anything. If there's already a changelog out htere, I'd appreciate any hint where to find it.

**Comment by emanuelpalm** [comment]
@awoSYS I would love for it to be possible to parse the change log, which would make it easier to use it programmatically.

I'm not quite sure what the best path forward is, however. My gut feeling is that there are quite a few things that need to be settled before recommendations surrounding change logs would become relevant to consider. Knowing that you are interested in this is great, however, as it means that we can reach out to you when it becomes relevant. We have, for example, talked about semantic versioning within the project, but that is also something I believe is being pushed into the future. About the time that will be picked up, I think it could be time to start talking about change logs.

@jerkerdelsing Any thoughts about this?

**Comment by jerkerdelsing** [comment]
We consider te release template solves this issue.
