### ISSUE TITLE
Cloud Bootstrapping, Monitoring and Management

### ISSUE THREAD

**Issue by emanuelpalm** [eclipse-arrowhead/roadmap#3]
__EDIT:__ This issue is not very up to date with the current developments on cloud bootstrapping. I will replace it with a new issue at some point in the future. The gist is that the two first systems mentioned below will be called the _Device Agent_ and the _Device Supervisor_. Other names are likely to also change.

With the aim of making it more straightforward to evaluate Arrowhead and deploy fresh systems, I propose that two new systems be created and one be modified or remade. The systems are:

1. the __Device Bootstrapper__ (DB),
2. the __Local Cloud Device Bootstrapper__ (LCDB), and
3. the __Local Cloud Manager__ (LCM) (redesign of the existing [Management Tool](https://github.com/arrowhead-tools/mgmt-tool-js)).

The idea is that an operator wishing to bootstrap a new Arrowhead cloud can install the DB system on each device to make up that cloud, as well as the LCDB system on the device intended to manage the cloud. When the LCDB system starts, it will broadcast its existence on its local network at a regular interval. When a DB system receives this broadcast, it registers ifself with the LCDB system, which marks it as being _requesting on-boarding_.

The LCM system provides a graphical user interface for the LCB system (and also for the Service Registry, Orchestrator, Authorization and Gatekeeper systems). Among other things this means that an operator could review a list of all devices that have requested on-boarding, and then click to accept certain devices. The LCM system further enables the operator to install and manage any systems on the devices running the DB system. In the context of evaluating Arrowhead or testing ideas, the LCM system could be capable of starting both a LCB and DB system on its own device, which enables the operator to quickly design its own system-of-systems on its device by clicking though the graphical interface.

# New Systems

Facilitating this type of system-of-systems requires the following new systems:

## Device Bootstrapper (DB)

__Purpose:__ To allow for a LCB system, potentially located on another device, to install, uninstall, start, stop and monitor arbitrary processes on the device running it.
__Consumes:__ On-Boarding*, Device Discovery, System Discovery, Service Discovery, _Local Cloud Bootstrapping_.
__Provides:__ _Device Bootstrapping_, _Device Management_, Monitoring (a.k.a. [Monitorable](https://github.com/eclipse-arrowhead/core-java-spring/blob/pde/documentation/plant-description-engine/monitorable-sd.md)**).

\* ~~The current variant of the [On-Boarding](https://github.com/eclipse-arrowhead/core-java-spring/blob/master/documentation/onboarding/ReleaseNotes-4.1.3-Onboarding.pdf) service does not seem to allow for there to be any time between the submission of an on-boarding request and its acceptance, which is required by this proposal. This means that either the current on-boarding service needs to be extended or that another one is created. @mzsilak What do you think? Am I missing something?~~ Resolved. See https://github.com/eclipse-arrowhead/roadmap/issues/3#issuecomment-820263341.

** The current variant of the [Monitorable](https://github.com/eclipse-arrowhead/core-java-spring/blob/pde/documentation/plant-description-engine/monitorable-sd.md) service only provides a function for requesting system data. Would another function for requesting device data be a suitable addition? @jronnberg Another idea is to create a more specific _Device Monitoring_ service that promises to be compatible with the Monitoring/Monitorable service, but gives extra guarantees about what fields will be provided in the SystemData/DeviceData messages?

## Local Cloud Device Bootstrapper (LCDB)

__Purpose:__ To allow for any number of registered DB systems to have processes installed, uninstalled, started and stopped, as well as to allow for the same devices to be monitored collectively.
__Consumes:__ Service Discovery (optional), Orchestration (optional).
__Provides:__ _Local Cloud Device Bootstrapping_, _Local Cloud Device Management_, _Local Cloud Monitoring_.

## Local Cloud Manager (LCM)

__Purpose:__ To allow for a human operator, via a intuitive and easily understood graphical user interface, to manage/administrate key systems of its cloud (significantly including the LCDB system). The management of the latter enables the operator to install arbitrary systems on any device running the DB system.
__Consumes:__ On-Boarding (optional), Device Discovery (optional), System Discovery (optional), Service Discovery (optional), Authorization (optional), Orchestration (optional), Gatekeeping (optional), _Local Cloud Device Management_ (optional), _Local Cloud Monitoring_ (optional).
__Provides:__ N/A.

# New Services

Our proposed new systems will provide the following new services:

## Device Bootstrapping

Allows for DB systems to receive broadcasts indicating what LCDB systems can be contacted, as well as be notified about acceptances and rejections to be on-boarded. The service is shut down as soon as a broadcast has been received that led to a successful initiation of the on-boarding procedure, which means that it will never be registered in a Service Registry.

__Service functions:__
- Notify about existing LCDB system (via IPv4 or IPv6 UDP multi-cast)
- Notify about acceptance of on-boarding procedure initiation
- Notify about rejection of on-boarding procedure initiation

## Device Management

Allows for processes to be installed, uninstalled, started, stopped and restarted on a specific device.

__Service functions:__
- Start a process (by name)
- Stop a process (by name)
- Restart a process (by name)
- List processes (started, stopped or all)
- Upload a file (binary, config, VM, etc.)
- Remove a file
- Install a process (name already uploaded files, specify environment variables, command line arguments and a name)
- Uninstall a process
- Reinstall/update a process (change environment variables, etc)
- List installed systems

## Local Cloud Device Bootstrapping

Allows for a DB system to request an LCDB system for the initiation of the local cloud on-boarding procedure.

__Service functions:__
- Request initiation of on-boarding procedure

## Local Cloud Device Management

Allows for processes to be installed, uninstalled, started, stopped and restarted on all registered devices. Also allows for a system operator to accept or reject registered on-boarding requests.

__Service functions:__
(the same ones as are provided by the Device Management service, with the difference that an additional field is specified in each message that identifies what devices are to receive a copy of the message)

## Local Cloud Monitoring

Allows for hardware, OS and runtime information of multiple devices to be collected at once.

__Service functions:__
- Get status of processes on certain devices
- Get static hardware and OS information from certain devices
- Get dynamic hardware and OS information (CPU usage, etc.) from certain devices
- Subscribe to hardware, OS and system status/changes feed (WebSockets/MQTT/etc.) from certain devices

# Unknowns
- ~~The LCDB will hold a form of registry of devices, or it cannot fulfill its intended function. Does this help or work against the [Device Registry](https://github.com/eclipse-arrowhead/core-java-spring/blob/master/documentation/device_registry/ReleaseNotes-4.1.3-DeviceRegistry.pdf)? Should the DB system provide the device registry service to be an alternative to using a dedicated device registry, or should it provide data to the device registry? @mzsilak~~ Resolved. See https://github.com/eclipse-arrowhead/roadmap/issues/3#issuecomment-820263341.
- ~~What kind of certificates should the LCDB provide to the DB systems? Device certificates? Would that mean that DB systems do not have system certificates but use device certificates instead? I guess it doesn't really need to consume any services at all except for the on-boarding one? @mzsilak @jerkerdelsing @tsvetlin~~ Resolved. See https://github.com/eclipse-arrowhead/roadmap/issues/3#issuecomment-820263341.
- ~~Is there any overlap between these systems and the Test Tool by BNearIT?~~ No, but there may very well be potential for synergies later on (concluded on meeting together with BNearIT representatives). 
- ~~What should the graphical user interface of the LCM system look like? @jerkerdelsing Should we assemble some kind of design group, or would you like me to spend time on a proposal myself in the future?~~ Representatives from BNearIT and myself will discuss the GUI.

**Comment by emanuelpalm** [comment]
I will add more details to this proposal later.

**Comment by jerkerdelsing** [comment]
Good proposal. To me 
- Device Bootstrapper and
- Cloud Bootstrapper 
can be started right away

**Comment by emanuelpalm** [comment]
I just had a discussion with @mzsilak about on-boarding and certificates, and this is what I took away from it. @mzsilak, please add any comments you may have on these thoughts.

# System Changes

## Device Bootstrapper (DB)

The DB should consume the services of the _On-Boarding Controller_ (OC), _Device Registry_ (DR) and _System Registry_ (SR). The OC is used to exchange some _shared secret_ or _vendor certificate_ for an _On-Boarding Certificate_. The DR is then used to register the device and exchange the On-Boarding Certificate for a _device certificate_. The device certificate is then used to request a _system certificate_ from the SR for the DB system itself, as well as any additional systems the DB is instructed to install at a later occasion. When systems are uninstalled via the DB, it makes sure these are deregistered via the same System Registry.

## Cloud Bootstrapper (CB)

The CB will not provide any on-boarding mechanism by itself. Rather, it will provide requesting DB systems with the information required to contact the OC (On-Boarding Controller), consisting of a _bootstrapping vendor certificate_ or _shared secret_ and its IP address, but only if they are explicitly approved by an operator.

# Advantages

The primary advantage of this more complicated procedure is that quite some work has already been made to verify its security. Having a single way of on-boarding devices also means that work can be reused.

# Disadvantages

The current implementations of the systems required to facilitate this form of device on-boarding are relatively memory hungry and slow to start. This means that using the CM (Cloud Manager) for evaluation purposes will require a longer than otherwise required time to wait for systems to start. This situation _may_ improve as more core systems are made using C++.

# Other considerations

@mzsilak, can new shared secrets be added to the On-Boarding Controller at runtime? Are they consumed/removed automatically once they have been used? From what I can tell, providing shared secrets to approved DB (Device Bootstrapper) systems would be the ideal way of helping them on-board.

**Comment by mzsilak** [comment]
Hello Emanuel,
multiple shared secrects are not supported at all, but this can be extended easily.

**Comment by emanuelpalm** [comment]
@mzsilak Good to know. We'll see what we do about it initially.

**Comment by tsvetlin** [comment]
@emanuelpalm Some aspects of the proposal are not clear for me, I'd like to set up a meeting with you to go over it.

**Comment by emanuelpalm** [comment]
@tsvetlin Not all aspects are clear to me either, but we sure can set up a meeting. I'll send you a message.

**Comment by emanuelpalm** [comment]
This issue has been replaced by:

- https://github.com/eclipse-arrowhead/core-c/projects/1
