### ISSUE TITLE
New Orchestrator Flag: Only IP Address response

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-arrowhead/roadmap#32]
Hello,

could you implement a new flag for the orchestrator that it only response services which have a provider with an IP address? Currently I have a problem that our IO-Link boxes only can handle IP addresses. DNS names are not usable. Therefore I think there could be other services/systems which can not handle DNS names.

KR,
BlackRose01

**Comment by tsvetlin** [comment]
Dear @BlackRose01,

Can your tiny IO-Link boxes resolve IPv6 addresses too, or IPv4 only?

**Comment by BlackRose01** [comment]
Hey @tsvetlin,

the IO-Link boxes only speak IPv4.

KR,
BlackRose01

**Comment by tsvetlin** [comment]
Three new ochestration flags are proposed by AITIA:
 * onlyIPAddress (only IP addresses IPv4 and IPv6 are returned)
 * onlyIPv4Address (only IPv4 addresses are returned)
 * onlyIPv6Address (only IPv6 addresses are returned)

For the current implementation we have two ideas in mind, those will be discussed during the next roadmap meeting.

**Comment by jerkerdelsing** [comment]
+1 from me.
