### ISSUE TITLE
Common services like Echo and Monitor to be standardised across core system 

### ISSUE THREAD

**Issue by jerkerdelsing** [eclipse-arrowhead/roadmap#38]
There starts to be a couple of services which show up at several core systems
- Echo
- Monitor

The Echo service available in a couple of core systems seams to be slightly different documented and implemented in several of the core system.

The Monitor service is requested from application system by a couple of new and upcoming core support systems, e.g. PlantDescriptioEngine, QoS, ... 

Can we device a common Echo service?
probably YES. Can we provide this in as a library service?

Can we define a common Monitor service?
Maybe, or can we find an approach where application system can have a library Monitor service which can be used by developer.

**Comment by BlackRose01** [comment]
Hello,

here is another solution for monitoring a java application (https://www.baeldung.com/spring-boot-actuators). Maybe it is better than metrics because it is more independend from prometheus and it runs on a management port (different web port, use other certificates, extendable).

KR,
BlackRose

**Comment by jerkerdelsing** [comment]
@Per O to report on industry requirements at next Roadmap WG in Feb.

**Comment by jerkerdelsing** [comment]
@PerOlofsson to be addressed in the back box v.5.0 documentation

**Comment by emanuelpalm** [comment]
This issue has bearing on:

- https://github.com/eclipse-arrowhead/core-c/issues/13
- https://github.com/eclipse-arrowhead/core-c/issues/4

**Comment by jerkerdelsing** [comment]
A SysMonitor SysD and Monitor SD is available in v5.0 documentation.
The issue is thereby closed.
