### ISSUE TITLE
Documentation template review - AITIA

### ISSUE THREAD

**Issue by tsvetlin** [eclipse-arrowhead/roadmap#42]
Dear Jerker,

We've reviewed the documentation, we are very satisfied with the template. We have some questions and found some typos.

**SysD:** 
typo: Stateful is the correct word not statefull
Blaock -> block
eclispe -> eclipse (in the github link)
cheching -> checking

How this service is meant to be used -> How this system is meant to be used
functoinal -> functional

prodiuced -> produced
referencen -> reference
updatees -> updates

1.3 System properties:

- Data stored by the system: what does this exactly means? Should I vaguely describe what the system stores? For example: The Service Registry stores service related data?
- What do we mean by non functional properties? Could you please provide an example?
- What do we mean by power saving properties? Could you please provide an example?
- What do we mean by Important Delimitations? Could you please provide an example?

**SysDD:**
typos:
Arrowehad -> Arrowhead
prefereable -> preferable
descibe -> describe
Forr -> for
configurtion -> configuration
statefull -> stateful
blow -> below
keept -> kept
updatees -> updates

Stateful - stateless: 2.4 looks like a duplicate of 2.2 and 2.3. What should we write here, which wasn’t previously written? Could you please provide an example?

3. Services: What should we write as Library ref when describing core system services? Why is the Library ref necessary and what is its purpose? Kalix is a bad example since it is not being actively maintained.

**SD:**
typo:
Arrowehad -> arrowhead
folowing: following
updatees -> updates

Contents 3: Service Interface, subpoints should be operations and not functions (function was renamed to operation by Emanuel)
3.1 operation AA
3.2 operation BB

3 Service Interface
Register is has a response: ServiceRegistryRequest
Echo has a string response currently,
Query(ServiceQueryForm,ServiceQueryList) -> Query(ServiceQueryForm) : ServiceQueryList

The diagrams are not in line with the text but at the end and makes understanding hard, they should be at a separate point: 5 Workflow

**IDD:**
typo:
Comprerssion -> Compression
protcol -> protocol
follwoing -> following

Contents 2 Service Operations
2.1 operation Register
all mentions of function should be renamed to operation

**Comment by borditamas** [comment]
Please note that I have made some progress on the ServiceRegistry documentation based on the templates, but without the concept of "operation". They are not ready yet, but the current states of the docs are linked to the wiki in order to see them as a whole. (To see how the Wiki and a the SysD, SysDD, SD and IDD can cooperate).

My drafts are available from these wiki pages:
https://github.com/eclipse-arrowhead/core-java-spring/wiki/service%E2%80%90register
https://github.com/eclipse-arrowhead/core-java-spring/wiki/Service-Registry-Overview

**Comment by PerOlofsson-Sinetiq** [comment]
Comments on the SD template (pdf version)

**General comment/question**
Should we include sequencing in the SD document, for example if an operation has a temporal dependency to another operation. If so, I would like to see that as a top level chapter.

**Specific comments on chapters/sections**
Chapter 1 Overview
I would like to exchange the text from [brief description of..] to [a description of service capabilities excluding implementation details].

Chapter 2.3 and 2.4 - Remove since they do not add meaning to the template.

Chapter 3 Information Model
Remove the sentence "An overview of the data types is.."

Chapter 3.1 
Change chapter name to correspond to ch 2, to "3.1 struct aa" and add some template text that describes that the chapter describes a data structure that is used in operation 2.1.
Add a description to the table.

Chapter 3.2
Same comment as to 3.1, except that struct should be "bb".

Chapter 3.3
Same comment as 3.1, except that struct should be "response".

Figure 2 & 4 & 3 - Remove or move to a separate chapter according to general comment.

Chapter 4.1 Amendments
The primitives table should be located in chapter 3.4?

**Comment by PerOlofsson-Sinetiq** [comment]
Comments on the IDD template (pdf version)

**General comment/question**
Should we have a template that states HTTP/TLS/JSON. This delimitation makes the template almost useless for any other communication strategy.

The example used in the template (Service registry services) is too complex. Using for example a temperature service should be more adequate in this document. The operations and the data structures should highlight the information and the order of the document rather that documenting the Service Registry services.

**Specific comments on chapters/sections**
Figure 2 seems to be misplaced, or is is an appendix?

**Comment by UlfSlunga-Sinetiq** [comment]
Comments on the IDD template (pdf version)

**General comment/question**

Would it be possible to describe format of json messages using a json schema? i.e. referring/linking to a formal specification instead of defining details in a word-document.
Much of the details in chapter 2 and chapter 3 should be possible to define in schemas. A schema would be useful for any implementation and reduce the risk of specifications not being updated.

**Comment by jerkerdelsing** [comment]
JSON schema is very attractive to use. I don't think we should mandate JSON schema since I presume that there are data model which may not fit into a JSON schema.

Please use JSON schema when ever possible. I can add such comment to the template.

**Comment by UlfSlunga-Sinetiq** [comment]
Comments on the SD template (pdf version)

**3.4 Primitives**

Does the extra Information model example (_Figure 3_) add anything to the template? Is it enough with _Figure 2_?

Information model examples could/should be moved to a separate sub-chapter 3.x. Does not really belong to _3.4 Primitives_

**Comment by jerkerdelsing** [comment]
> Comments on the IDD template (pdf version)
> 
> **General comment/question** Should we have a template that states HTTP/TLS/JSON. This delimitation makes the template almost useless for any other communication strategy.
> 
> The example used in the template (Service registry services) is too complex. Using for example a temperature service should be more adequate in this document. The operations and the data structures should highlight the information and the order of the document rather that documenting the Service Registry services.
> 
> **Specific comments on chapters/sections** Figure 2 seems to be misplaced, or is is an appendix?

HTTP/JSON/TLS should be viewed as example of protocol, encoding and payload encryption to be used.

> Dear @jerkerdelsing and @emanuelpalm ,
> 
> I'm working on the documentation of core-java-spring implementation based on these templates, but having troubles with the service-operation structure.
> 
> Since the concept of "operation" is not existing at all in the current core-java-spring implementation (due to an early missunderstanding as we've learned from Emanuel), the documentation would not cover the real implementation if I would keep this structure. It would generate confusions in the users that the docs are talking about the opeartions, but when for example it comes to the ServiceRegistryRequest input json in the IDD, the user will see that there is no operation list and won't understand how he/she will be able to register his/her XYZ service with AA, BB, CC operation. Also, others whos already have providers written for this implementation, will have the same troubles of documenting their services in the service-operation structure.
> 
> According to my opinion the most important now in this situation is to have an accurate documentation about the real implementation, therefore I would leave out the concept of operation from the docs of core-java-spring v4.4.0. We could say that the implementation of the operation concept will come with the 5th generation of the framework. What are your views on this?
> 
> **BTW,** I think this issue should be transferred to RoadMap repo, because the LaTex templates are uploaded there.

I don't see the issue. The modelling made based on previous documentation have used operations in SysML to model the the different "operations" possible of a service.
See the bdd of the ServiceRegistry below.
![SR](https://user-images.githubusercontent.com/3283337/151984007-4f22fd83-115a-4365-933b-6ddad3173fb3.png)

**Comment by jerkerdelsing** [comment]
> Comments on the SD template (pdf version)
> 
> **3.4 Primitives**
> 
> Does the extra Information model example (_Figure 3_) add anything to the template? Is it enough with _Figure 2_?
> 
> Information model examples could/should be moved to a separate sub-chapter 3.x. Does not really belong to _3.4 Primitives_

The size of the figures moved them after <<section 31., 3.2 and 3.3 where they are referenced. The alternative is to have a lot of blank space to have the figures perfectly aligned with the text. Have updated the SD template page outline. I hope its better now.

**Comment by fblomstedt41** [comment]
**SySDD**

The SysDD can/shall ref. to all existing system specific documentation. Ex. Manual/User Guide/System description.

Information about implementation of all of the IDD's shall be clear. The slightest difference or deviation must be clarified within this document. Should we have a chapter named Deviation for each IDD implementation?

**Comment by jerkerdelsing** [comment]
My updates of the templates with respect to the below comment.

> Comments on the SD template (pdf version)
> 
> **General comment/question** Should we include sequencing in the SD document, for example if an operation has a temporal dependency to another operation. If so, I would like to see that as a top level chapter.

Added to Sec 1.3 Important delimitations and dependencies

> 
> **Specific comments on chapters/sections** Chapter 1 Overview I would like to exchange the text from [brief description of..] to [a description of service capabilities excluding implementation details].
> 

FIXED

> Chapter 2.3 and 2.4 - Remove since they do not add meaning to the template.
> 

They are kept there to indicate the possibility of having multiple operations of one service,

> Chapter 3 Information Model Remove the sentence "An overview of the data types is.."

Reworded to EXAMPLE:

> 
> Chapter 3.1 Change chapter name to correspond to ch 2, to "3.1 struct aa" and add some template text that describes that the chapter describes a data structure that is used in operation 2.1. Add a description to the table.
> 
> Chapter 3.2 Same comment as to 3.1, except that struct should be "bb".
> 
> Chapter 3.3 Same comment as 3.1, except that struct should be "response".

FIXED

> 
> Figure 2 & 4 & 3 - Remove or move to a separate chapter according to general comment.

Repaginated

> 
> Chapter 4.1 Amendments The primitives table should be located in chapter 3.4?

Repaginated

**Comment by PerOlofsson-Sinetiq** [comment]
Comments on the SysD Document (pdf version)

**General comments/questions:**
-

**Specific comments on chapters/sections:**

Chapter 1.2 How this system is meant to be used
The sentence "Usage Scenarios shall be described" is unclear. I don't think that the SysD shall contain sequence diagrams that shows interaction with other black box descriptions. 
Chapter 1.3.2 and 1.3.3 are not relevant in a Black Box description, rather they should be described in a SysDD. The other 1.3.x chapters are OK as long as no implementation details are described.

Chapter 2 Services
There should be a subchapter describing produced services and one subchapter for describing consumed services. 
It could be a good idea to separate application services and core services in either the chapters above or keep them in a separate chapter.

Chapter 3 Security
There should be a overview section in the chapter to allow for "setting the scene" for the security landscape. The listed bullets should be stated as examples of information in succeeding subchapter/s.

**Comment by PerOlofsson-Sinetiq** [comment]
> HTTP/JSON/TLS should be viewed as example of protocol, encoding and payload encryption to be used

Ok. I would still like to emphazise in the template that this set of communication strategy is an example!

**Comment by jerkerdelsing** [comment]
> 

@borditamas 

This is one of the major flaws in the Java implementation where the assumption has been that http REST is the only protocol to be used in Arrowhead.
Arrowhead approach is to be protocol agnostic and that one should be able to reach a service using multiple protocols.
The ServiceRegistry produced service have since long been ServiceDiscovery. The ServiceDiscovery service have four different operations, register, unregister, query and echo.

In my. mind this will lead to an issue for both the ServiceRegistry and the Orchestration implementation.

**Comment by jerkerdelsing** [comment]
> > HTTP/JSON/TLS should be viewed as example of protocol, encoding and payload encryption to be used
> 
> Ok. I would still like to emphazise in the template that this set of communication strategy is an example!

@PerOlofsson-Sinetiq 
The updated template in GitHub says so.

**Comment by jerkerdelsing** [comment]
My response in-line below:

> Comments on the SysD Document (pdf version)
> 
> **Specific comments on chapters/sections:**
> 
> Chapter 1.2 How this system is meant to be used The sentence "Usage Scenarios shall be described" is unclear. I don't think that the SysD shall contain sequence diagrams that shows interaction with other black box descriptions. Chapter 1.3.2 and 1.3.3 are not relevant in a Black Box description, rather they should be described in a SysDD. The other 1.3.x chapters are OK as long as no implementation details are described.

The intention is to provide a high level understanding what the devlope had in mind when defining the system. Thus I think that the requested info is relevant. The description should be narrative with no implementation details.
Template updated accordingly.

> 
> Chapter 2 Services There should be a subchapter describing produced services and one subchapter for describing consumed services. It could be a good idea to separate application services and core services in either the chapters above or keep them in a separate chapter.

Fixed in template
> 
> Chapter 3 Security There should be a overview section in the chapter to allow for "setting the scene" for the security landscape. The listed bullets should be stated as examples of information in succeeding subchapter/s.

Template updated accordingly

**Comment by jerkerdelsing** [comment]
See my comment in-line below
> **SySDD**
> 
> The SysDD can/shall ref. to all existing system specific documentation. Ex. Manual/User Guide/System description.

This can be a tricky updating cycle.
References are made to the corresponding SysD, the SD and IDD implemented.
A clear direction on which document that is sited is provided in the updated template.
 
> Information about implementation of all of the IDD's shall be clear. The slightest difference or deviation must be clarified within this document. Should we have a chapter named Deviation for each IDD implementation?

Clarified in update template!

**Comment by borditamas** [comment]
@jerkerdelsing
I know and understandand, but still, I can't create an implementation documenatation which is not covering the reality. And I'm not suggesting to change the offical templates in general, I'm only saying that for core-java-spring 4.4.0 the docs have to differ from the offical templates (in this service-operation structure). And we could highlight this deviation for example somewhere in the wiki plus state that spring-java-core 5.0 will fix this issue

**Comment by tsvetlin** [comment]
@jerkerdelsing 
We understand the architectural point, but in order to change it in the current implementation, it would lead to breaking changes, thus backward compatilibity issues. Which we have to avoid until Arrowhead 5.0.0
The current implementation of Service Registry does not include the Service Discovery as a service, but its operations as individual services. (Echo, Register, Unregister, Query). When implementing this service, we followed the AH 3.X, 4.1.2 structure, which already contained this deviation.

The authorization enables access right to services, and not operations offered by services currently. This could be changed not earlier than 5.0.0, because of the backward compatibility issue.

The orchestrator was built upon the same principle, resulting the same issue. This also could be changed not earlier than 5.0.0, for the same reason.

I see that 5.0.0 can be the first JAVA-Spring reference implementation, that follows the new documentation template.
Sadly, for 4.X we must deviate.

I hope you can understand that.

**Comment by jerkerdelsing** [comment]
@tsvetlin @borditamas 

I do understand the deviation. Please proceed with documentation where each service only have one operation.

Jerker

**Comment by PerOlofsson-Sinetiq** [comment]
> @jerkerdelsing We understand the architectural point, but in order to change it in the current implementation, it would lead to breaking changes, thus backward compatilibity issues. Which we have to avoid until Arrowhead 5.0.0 The current implementation of Service Registry does not include the Service Discovery as a service, but its operations as individual services. (Echo, Register, Unregister, Query). When implementing this service, we followed the AH 3.X, 4.1.2 structure, which already contained this deviation.
> 
> The authorization enables access right to services, and not operations offered by services currently. This could be changed not earlier than 5.0.0, because of the backward compatibility issue.
> 
> The orchestrator was built upon the same principle, resulting the same issue. This also could be changed not earlier than 5.0.0, for the same reason.
> 
> I see that 5.0.0 can be the first JAVA-Spring reference implementation, that follows the new documentation template. Sadly, for 4.X we must deviate.
> 
> I hope you can understand that.

A side note: This approach will create a lot of IDD:s, since one service should be corresponding to one interface description. It would also be somewhat cumbersome to map one SD (Service Discovery) to four IDD:s (Echo, Register, Unregister and Query). I don´t say it is impossible, but it will definitely require some brain effort to make it work out well.

A different and maybe easier way would be to create an IDD with the amended four operations and state in the SysDD for the Service Registry that there is an implementation dependency that split the Service Discovery service into four services??
