### ISSUE TITLE
GSoSD Arrowhead Core Systems 5.0: System-service matrix in GSoSD?

### ISSUE THREAD

**Issue by PerOlofsson-Sinetiq** [eclipse-arrowhead/roadmap#56]
There has been a discussion whether the System-Service Matrix should be a part of the SoSD. 

Arguments for having it is for example the design-time availability to see existing possibilities of interactions. Another argument is the ability to plan coming interactions and set the scene for new generations of s system-of-system.

Arguments against it is for example that it fills no purpose in a run-time situation and that it might get too large to give the visibility of the service landscape in a system-of-system. It would also state current implementation details that should not be present in an architecture document.

**Comment by emanuelpalm** [comment]
My understanding of the outcome of #54 is that this issue will be addressed by @PerOlofsson-Sinetiq and myself in a later version of the GSoSD, without us discussing this here. I'm closing this issue to reflect this. If any of you are opposed to this interpretation, please go ahead and reopen it.
