### ISSUE TITLE
GSoSD Review Discussion Point 1: Should Arrowhead systems be "lazy" (passive) or "active" (proactive)?

### ISSUE THREAD

**Issue by PerOlofsson-Sinetiq** [eclipse-arrowhead/roadmap#58]
We need to make sure that the architecture in the GSoSD are capable of adressing a flora of systems, ranging from systems that basically just starts up and register themselves in appropriate registries to advanced systems that handle for example orchestration by themself.

Should we create use-cases that describes this situation? Are there other ways to incorporate these requirements?

**Comment by PerOlofsson-Sinetiq** [comment]
I suggest the following approach to the issue:
1. We define the terms "active systems" and "passive systems".
2. We come up with a suggestion of the Arrowhead 5.0 principle of interaction with active/passive systems.

**Comment by borditamas** [comment]
**AITIA's view on the subject:**
We think that a service oprertion could be passive or active (not a system itself) depending on the purpose of operation. Could you please explain why should we define such a restriction for the Arrowhead Systems? What made this question coming up?

**Comment by PerOlofsson-Sinetiq** [comment]
> **AITIA's view on the subject:** We think that a service oprertion could be passive or active (not a system itself) depending on the purpose of operation. Could you please explain why should we define such a restriction for the Arrowhead Systems? What made this question coming up?

No, i do not associate the operations with the term "active"/"passive". 

The question adresses whether systems can make its own decisions and act within the Arrowhead cloud (an "active system") or if they are commanded to act on behalf of some other system or an operator (a "passive system").

I think this is the reason for the definition point of this issue.  I´ll adress that in the following post.

**Comment by PerOlofsson-Sinetiq** [comment]
I would like to propose the following definition of "active" and "passive" systems:
**- Active systems**
Active systems are systems that perform actions on existing internal and external data. These systems can initiate orchestration by themself in order to carry out tasks. These systems are acting in various levels of autonomy. 
**- Passive systems**
Passive systems are systems that wait for external stimuli before performing any execution. These systems probably have less computational capabilities than the active counterpart. These systems rely on the Arrowhead Core services to a large extent to get necessary data.


The two types of systems are putting different requirements on the Arrowhead Core Services. The more "active" a system is, the more of the core capabilities are present within the application system itself. More "active" systems will require more tolerant core services. On the contrary, the more "passive" a system is, the more responsibility is put on the core services to provide data to the application system.

**Comment by PerOlofsson-Sinetiq** [comment]
Another aspect, related to the legacy integration. Lots of legacy systems tend to lean at the "active" system paradigm, with complex and holistic approach to the stated requirements. In the future, where we might se more microservice / microsystem solutions, a more "passive" approach might be present. However, the Arrowhead Framework will always have to deal with legacy systems that tries to lock users into their solution.

**Comment by jerkerdelsing** [comment]
Seams that the meeting July 28 agrees.

**Comment by emanuelpalm** [comment]
A key reason why we should allow both active and passive systems is because we cannot prevent systems from being active. @PerOlofsson-Sinetiq raised this point during the meeting.

**Comment by jerkerdelsing** [comment]
17/8 meeting Agreed to Pers proposal.  The implications of resilience need to be added to GSoS. Per o implement in GSoSD.
