### ISSUE TITLE
GSoSD Review Discussion Point 2: What "specification documents" should exist apart from the GSoSD, the Concepts Reference and the Foundational Principles documents? What is the scope of each document? 

### ISSUE THREAD

**Issue by palvarga** [eclipse-arrowhead/roadmap#66]
Documentation is pain, but we need reference points and common grounds.
Historically Arrowhead had various types of documents - Definitions, Cookbook, then the types according to the documentations structure SoSD(D), SysD(D), SD, IDD, CP, SP. We had generic reference examples/descriptors to these.

The current common ground is the Generic SoSD (GSoSD), the Concepts Reference, and the Foundational Principles.
These are generic Arrowhead documents by Arrowhead Core Experts.
Domain engineers and experts still have to create SoSD, SysD, SD and IDD documents and grow the Arrowhead capable universe of SoSs, systems and services.

Beside the GSoSD, Concepts Reference, and the Foundational Principles, it makes sense to provide common, generic specs as:
- Example SoSD, SysD, SD and IDD documents
- A one-pager on how to make the (basic) Arrowhead Reference implementation run in a new environment is less than 30 minutes.
- Application System Skeleton
- Arrowhead Reference Implementation message sequences and APIs
- 
- ... further ideas and detailed content is the discussion topic of this issue

**Comment by jerkerdelsing** [comment]
No diverting comments so far. From the meeting of July 27.

**Comment by emanuelpalm** [comment]
Three proposals for additional specification documents:
1. __Documentation Specification__, which describes in details exactly how to write the architectural Arrowhead documents (SySD, SoSD, IDD, etc.).
2. __Normative Use Cases__, which describe use cases that are understood to be good representations of diverse settings where Arrowhead could be applied.
3. __Normative Hardware__, which describe major of classes of hardware that core system implementation must target at least one of (embedded, constrained, simple, high-performance, etc.).

**Comment by jerkerdelsing** [comment]
Pal will update the GSoSD

**Comment by jerkerdelsing** [comment]
Introduced into the GSoS by Raymond and Pal
