### ISSUE TITLE
GSoSD review discussion Point 4: How do we name the Orchestration System (Core) and the Choreography System (Support) such that we avoid unnecessary confusion from the Microservices communities?

### ISSUE THREAD

**Issue by flarrinaga** [eclipse-arrowhead/roadmap#67]
The purpose of this issue is to agree on a naming scheme that avoids confusion between these two systems. During the roadmap meetings this question was brought up. We queried ChatGPT for a naming proposal based on the systems functionality. The naming proposal given by ChatGPT can be found in the following document along with a name "migration" proposal. [Arrowhead naming proposal for Orchestrator-Choreographer.docx](https://github.com/eclipse-arrowhead/roadmap/files/11879045/Arrowhead.naming.proposal.for.Orchestrator-Choreographer.docx)
This issue is open to further naming proposals.

**Comment by emanuelpalm** [comment]
I can't remember who brought it up during our last meeting (was it @PerOlofsson-Sinetiq?), but someone suggested to call it "_service_ orchestration" and "_software_ orchestration". What I like about this proposal is that we can keep using the word "orchestration". One definition of _orchestrate_ is _["to arrange or combine so as to achieve a desired or maximum effect"](https://www.merriam-webster.com/dictionary/orchestrate)_. To me that neatly captures the idea of making sure the right thing (service record or software artifact) ends up in the right place.

**Comment by emanuelpalm** [comment]
I would like us to avoid terms such as _mediator_ and _engine_ in the names of Arrowhead systems, and I believe we should only use the term _broker_ for a system involved in message brokering (Publish-Subscribe).

### Service Mediator

The reason for avoiding _mediator_ is that __all__ computer software mediate something. Computer programs do not have their own desires. They mediate the intents of their programmers or owners. They receive instructions and forward instructions to other software and hardware systems. What does a _service mediator_ really _mediate_?

In the same sense, all computer programs _manage_ resources and _handle_ data. While these terms (manager and handler) were not included in your proposal, I just want to highlight that these words have the same problem and should not be used for other Arrowhead systems.

### Service Broker

In my mind at least, the term "broker" is so tied up to the Publish-Subscribe paradigm that I'm hesitant to use it for anything else than that. I'm not going to say that I'm definitely against it, however.

### Orchestration Engine

In the context of software, the term _engine_ means something like "the thing makes another thing work at a fundamental level". A _graphics engine_ makes _graphics_ work, while a _search engine_ makes _search_ work, and so on. How does an _orchestration engine_ make _orchestration_ work?

### Orchestration vs. Choreography

The definitions of orchestration and choreography presented by ChatGPT seem to align with what is said [in this StackOverflow question](https://stackoverflow.com/questions/4127241/orchestration-vs-choreography). If we follow this definition, there is no Arrowhead system that is engaged in choreography, right? The choreographer just becomes another kind of service orchestration system? Or perhaps an "orchestration coordinator" or an "orchestration workflow agent"?

**Comment by flarrinaga** [comment]
Thank you for your input. I agree to your comments. 
So at this stage we have the following proposal:
For the Orchestration System (Core), the proposal is **Software Orchestration System** (Core)
For the Choreography System (Support), the proposal is **Service Orchestration System** (Support).

This last system could also be called **Workflow Orchestration System** (Support) since it is in charge of managing a series of tasks/services in a workflow from a central point (orchestrator).

Please, give us your feedback on these naming proposal.

Regards

**Comment by emanuelpalm** [comment]
@flarrinaga 

As far as I understand it, the Arrowhead core system that has been referred to as the Orchestration System up until this point orchestrates service records, not software artifacts. An example of the latter is [HashiCorp Nomad](https://www.nomadproject.io/).

**Comment by emanuelpalm** [comment]
@flarrinaga Yes, pretty much so.

Using _Workflow_ in the new name of the Choreography system is your idea, however. I'm not taking credit for that. I think it is a suitable name. :+1:

To be very explicit then, this is what I endorse (none of the name ideas are mine):

| Current | Proposed |
|:--------|:----------|
| Orchestration System | Service Orchestration System |
| Choreography System | Workflow Orchestration System |

**Comment by borditamas** [comment]
**AITIA view:**

We think that here the continuity and consistency is more important towards to the existing Arrowhead community then the alignment with other communities. As long as the word expresses the purpose of the system, every community will be able to adapt to it.

We can support the above mentioned proposal:

> Current | Endorsed
> -- | --
> Orchestration System | Service Orchestration System
> Choreography System | Workflow Orchestration System

**Comment by jerkerdelsing** [comment]
Short discussion on naming no final conclusion reached. Discussion on merging of the v4 Choreography system and Workflow Manager system.

**Comment by DavidRutqvist** [comment]
> Current	Endorsed
> Orchestration System	Service Orchestration System
> Choreography System	Workflow Orchestration System

I could be OK with this. I agree with the new renaming of Choreography System into Workflow Orchestration System.

Since the current Orchestration System coordinates what systems talk to what services without specifying any order of tasks I would call this Service Choreography System instead.

The word choreography emphasizes the autonomousness of systems more than orchestration. An orchestration system would be more "call service X then service Y" whereas a choreography system would be more "You should call service X and Y however you like".

**Comment by jerkerdelsing** [comment]
From 17/8 meeting. Seams we have an agreement. JD to contact Felix on updating this to the GSoSD.

**Comment by flarrinaga** [comment]
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">It seems we have reached an agreement on the naming of the services (as table below)</p>

Current | Endorsed
-- | --
Orchestration System | Service Orchestration System
Choreography System | Workflow Orchestration System

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Consequently I will close the issue. Thank you all for your contributions</p>
</body>
</html>
